# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Review Deno Code"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
jobs:
  main:
    name: "${{matrix.run_on}}"
    permissions:
      contents: "read"
    strategy:
      matrix:
        run_on:
          - "ubuntu-latest"
        run_sub:
          - false
        include:
          - run_on: "macos-latest"
            run_sub: true
          - run_on: "windows-latest"
            run_sub: true
      fail-fast: false
    uses: "hugoalh/hugoalh/.github/workflows/call-review-deno-code-2.yml@main"
    with:
      run_on: "${{matrix.run_on}}"
      run_sub: "${{matrix.run_sub}}"
      deployment_jsr: true
      deployment_npm: true
